Coba Dilihat Lagi
Manpro-B1/Akreditasi2020 pull request #10
Opened 2019-10-28 04:21 UTC by vosetrick

2019-10-28 05:58 UTC, william-walah requested changes
Tolong dirubah:
- [x] path buat referensi link (contoh ke tata pamong) jangan kasih absoulte (e.g. localhost/akreditasi2020/...), karena udah didalam 1 folder yang sama, langsung aja nama filenya (e.g. href="TataPamong.php")
- [x] Buat navbar (menu kiri) jangan pakai "X" (di Sidebar.php), tapi pake "&times"

2019-10-28 13:03 UTC, william-walah approved these changes

2019-10-28 13:18 UTC, liondy commented
Sorry @vosetrick buat ke master, lu harus nge merge dulu ke modul lu (homepage), baru bisa ke master karena disini gw gada tombol approvalnya (kecuali pakai priviledges administrator kaya dipaksa gitu). Thanks

2019-10-29 03:09 UTC, liondy approved these changes

2019-10-29 03:09 UTC, merged